<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-GRVVO5IQ" failures="36" tests="243" name="dsAlgo_Runner.TestRunner" time="94.747" errors="0" timestamp="2025-04-15T19:55:52 EDT" skipped="0">
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.496"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.469"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.030"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.262"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.269">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:527)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.407"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.511"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.497"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.497"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.291"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.286"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.291"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.095"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.615"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.112"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.579"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.128"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="4.391"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.117"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.644"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.323">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:77)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.199"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.660"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.532"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.577"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.313"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.325">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:207)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.103"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.111"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.159"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.061"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.153"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.374"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.659"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.276"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.057"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.412"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.057"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.419"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.114"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.291">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:62)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.272">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:217)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.301"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.482"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.477"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.069"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.098"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.180"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.277">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:372)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.432"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.265"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.480"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.031"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.333"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.137"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.116"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.130"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.212"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.287"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.058"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.583"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.308"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.061"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.117"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.029"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.444"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.303"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.529"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.767"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.306">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message_in_console(Array_SD.java:242)
at ✽.The user see an error message "No Tests were Collected" in console(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:387)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.748"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.401"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.058"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.290"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.058"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.731"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.405"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.101"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.922"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.305">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:267)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.107"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.066"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.565"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.453"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.037"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.277">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:347)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.088"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.054"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.412"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.199"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.655"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.341"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.294"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.156"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.691"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.044"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.128"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.261">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:502)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.434"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.086"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.796"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.295"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.283"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.256"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.319"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.433"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.299">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:312)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.644"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.429"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.454"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.312"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.434"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.188"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.333">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:182)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.353"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.383"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.512"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.285">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:397)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.080"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.306"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.331"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.422"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.589"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.280"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.160"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.295"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.247"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.961"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.113"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.307"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.126"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.646"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.503"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.296">
    <failure message="expected [Submission successful] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:477)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.852"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.034"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.292"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.403"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.033"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.756"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.336">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:52)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.028"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.324">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:342)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.275"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.060"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.842"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.150"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.101"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.493"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.343">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message_in_console(Array_SD.java:242)
at ✽.The user see an error message "No Tests were collected" in console(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:127)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.273"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.451"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.307">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:442)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.148"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.289"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.331">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:137)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.321"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.328"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.141"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.413"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.710"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.142"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.265"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.275"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.058"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.663"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.326">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:102)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.170"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.327"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.286"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.268"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.262"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.126"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.527"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.299"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.406"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.298">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:467)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.503"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.463"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.034"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.057"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.045"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.065"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.272"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.302">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:87)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.286">
    <failure message="expected [Submission successful] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:322)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.829">
    <failure message="expected [Invalid username] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Invalid username] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Register_SD.the_user_is_not_able_to_see_error_msg_after_entering_invalid_data(Register_SD.java:107)
at ✽.The user is not able to see error msg after entering invalid data(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD02_Register.feature:37)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.125"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.606"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.338">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:362)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.222">
    <failure message="https://dsportalapp.herokuapp.com/linked-list/ expected [https://dsportalapp.herokuapp.com/linked-list/] but found [https://dsportalapp.herokuapp.com/question/4]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: https://dsportalapp.herokuapp.com/linked-list/ expected [https://dsportalapp.herokuapp.com/linked-list/] but found [https://dsportalapp.herokuapp.com/question/4]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.asserts.Assertion$10.doAssert(Assertion.java:176)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:172)
at dsAlgo_stepDefinition.LinkedList_SD.the_user_is_in_the_page_sign_in(LinkedList_SD.java:37)
at ✽.The user is in the "Linked list" page Sign in(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD06_LinkedList.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.039"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.663"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.020"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.142"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.548"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.106"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.332">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:192)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.312">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:232)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.359"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.181"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.384"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.274">
    <failure message="expected [Submission successful] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:452)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.368">
    <failure message="expected [Submission successful] but found [hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [hello]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:112)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.745"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.376"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.399"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.059"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.639"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.728"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.696">
    <failure message="expected [Invalid password] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Invalid password] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Register_SD.the_user_is_not_able_to_see_error_msg_after_entering_invalid_password(Register_SD.java:127)
at ✽.The user is not able to see error msg after entering invalid password(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD02_Register.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.546"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.059"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.305"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.262"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.243"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.154"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.381"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.405"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.251">
    <failure message="https://dsportalapp.herokuapp.com/home expected [https://dsportalapp.herokuapp.com/home] but found [https://dsportalapp.herokuapp.com/question/4]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: https://dsportalapp.herokuapp.com/home expected [https://dsportalapp.herokuapp.com/home] but found [https://dsportalapp.herokuapp.com/question/4]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.asserts.Assertion$10.doAssert(Assertion.java:176)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:172)
at dsAlgo_stepDefinition.DataStructure_SD.the_user_is_in_the_home_page_after_logged_in(DataStructure_SD.java:25)
at ✽.The user is in the Home page after logged in(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD06_LinkedList.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.062"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.623"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.299">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message_in_console(Array_SD.java:242)
at ✽.The user see an error message "No Tests were collected" in console(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:257)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.334">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message_in_console(Array_SD.java:242)
at ✽.The user see an error message "No tests were Collected" in console(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:517)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.529"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.382"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.111"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.108"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.296">
    <failure message="expected [Submission successful] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_success_message(Array_SD.java:213)
at ✽.The user see success message "Submission successful"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:242)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.354"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.229"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.062"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.059"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.315">
    <failure message="expected [Submission successful] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission successful] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Array_SD.the_user_see_an_error_message(Array_SD.java:191)
at ✽.The user see an error message "Error occurred during submission"(file:///C:/projectcompass/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD05_Arrays.feature:492)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.089"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.541"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.424"/>
</testsuite> <!-- dsAlgo_Runner.TestRunner -->
